plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.js

packageExtensions:
  "@eslint/eslintrc@*":
    peerDependencies:
      globals: "*"
      ignore: "*"
      lodash: "*"
      minimatch: "*"
